# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelogin', '0003_auto_20170903_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_details',
            name='contact_image',
            field=models.ImageField(blank=True, upload_to='images/contact_images'),
        ),
    ]
