# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 12:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simplelogin', '0005_auto_20170904_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_data', models.CharField(max_length=140)),
                ('recieve_contact_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieve_contact_name', to='simplelogin.contact_details')),
                ('sender_contact_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_contact_name', to='simplelogin.contact_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
