# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplelogin', '0006_contact_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_messages',
            old_name='recieve_contact_name',
            new_name='reciever_contact_name',
        ),
        migrations.RemoveField(
            model_name='contact_messages',
            name='sender_contact_name',
        ),
    ]
