# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplelogin', '0007_auto_20170917_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_messages',
            name='reciever_contact_name',
        ),
        migrations.AlterField(
            model_name='contact_messages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
