# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simplelogin', '0008_auto_20170917_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_messages',
            name='receiving_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
