# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 04:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simplelogin', '0009_contact_messages_receiving_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('user_image', models.ImageField(blank=True, upload_to='images/user_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='contact_details',
            name='contact_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
