# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 12:00
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplelogin', '0010_auto_20170918_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_messages',
            name='receiving_user',
        ),
        migrations.RemoveField(
            model_name='contact_messages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_image',
        ),
        migrations.AlterField(
            model_name='contact_details',
            name='contact_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999999999)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='contact_messages',
        ),
    ]
