# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 09:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelogin', '0014_auto_20170919_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_details',
            name='contact_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
