# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplelogin', '0018_auto_20170920_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
