# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simplelogin', '0020_auto_20170920_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
